name: Update README

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: 'Enter the Environment ID'
        required: true
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create edit branch
        run: git checkout -b readme-edit/${{ github.run_id }}

      - name: Setup Git config
        run: |
          git config --global user.name 'TheGupta2012'
          git config --global user.email 'harshit.11235@gmail.com'

      - name: Check Environment Validity
        id: check_env
        run: |
          ENV_ID="${{ github.event.inputs.env_id }}"
          # RESPONSE=$(curl -s "https://api.qbraid.com/environments/valid?envId=$ENV_ID")
          RESPONSE=true
          echo "::set-output name=valid::$RESPONSE"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: List files
        run: ls -la 

      - name: Update README
        run: |
          ENV_ID="${{ github.event.inputs.env_id }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          VALID="${{ steps.check_env.outputs.valid }}"
          python update_readme.py "$ENV_ID" "$REPO_OWNER" "$REPO_NAME" "$VALID"
        working-directory: ${{ github.workspace }}

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with dynamic image based on ENV_ID"
          git push origin readme-edit/${{ github.run_id }}
