name: Update README

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: 'Enter the Environment ID'
        required: true
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create edit branch
        run: git checkout -b readme-edit/${{ github.run_id }}

      - name: Setup Git config
        run: |
          git config --global user.name 'TheGupta2012'
          git config --global user.email 'harshit.11235@gmail.com'

      - name: Check Environment Validity
        id: check_env
        run: |
          ENV_ID="${{ github.event.inputs.env_id }}"
        # RESPONSE=$(curl -s "https://api.qbraid.com/environments/valid?envId=$ENV_ID")
          RESPONSE=false
          echo "::set-output name=valid::$RESPONSE"

      - name: Update README
        run: |
          ENV_ID="${{ github.event.inputs.env_id }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          echo "ENV_ID: $ENV_ID"
          echo "REPO_OWNER: $REPO_OWNER"
          echo "REPO_NAME: $REPO_NAME"

          if [ "${{ steps.check_env.outputs.valid }}" == "true" ]; then
            IMAGE_URL="https://qbraid-static.s3.amazonaws.com/logos/Launch_on_qbraid_with_env_white.png"
            ENV_PARAM="&envId=$ENV_ID"
          else
            IMAGE_URL="https://qbraid-static.s3.amazonaws.com/logos/Launch_on_qBraid_white.png"
            ENV_PARAM=""
          fi
          sed -i "s|\[<img src=\".*\" width=\"150\">\](.*)|[<img src=\"$IMAGE_URL\" width=\"150\">](https://account.qbraid.com?gitHubUrl=https://github.com/$REPO_OWNER/$REPO_NAME.git$ENV_PARAM)|" README.md


      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with dynamic image based on ENV_ID"
          git push origin readme-edit/${{ github.run_id }}

      - name: Create Pull Request
        run: | 
          gh pr create --title "Update README with dynamic image based on ENV_ID" --body "This PR updates the README with a dynamic image based on the ENV_ID" --base main --head readme-edit/${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}